### PR TITLE
[#34] Capture errors from async routes

### PR DESCRIPTION
**Pull request by gumberss**
# Issue

no issue

## Details
At this moment, if you throw an error in an async route, this error won't be caught for an error route. So this Pull Request want to fix it and make sure the errors will be handled correctly for the error route.

Before:
image

After:
image

Test code:
image

## CheckList

- [x] PR starts with no issue.
- [ ] Has been tested (where required) before merge to main.

### CODE REVIEW

**Comment by asos-craigmorten** [comment]
My days, I literally just clocked this myself last night - spooky timing! Thanks for the contribution 🙌

We might need to take a little care to ensure adding this async doesn’t regress features elsewhere, but fingers crossed it stays as simple as your changes.

Two things that come to mind:
1. We should also add async to the handle error method for consistency + it also suffers from this bug.
2. The tests appear to be failing, we should get on top of those 😊

I’ve actually got another branch open where I’m adding the long needed test coverage, and think this would be a good fit for the `regression.test.ts` or one of the error tests where currently we’ve only considered synchronous examples.

**Comment by asos-craigmorten** [comment]
@gumberss would you mind raising an issue on the repo - just in case someone looks through them and not the open PRs? Good for tracking (especially if turns out to be a bigger issue than the 2 line fix! 🤞 its not)

**Comment by gumberss** [comment]
Thanks for the advices :D!

1 - Of course, I must add async to error_handler as well!

2 - Before I create the pull request I tried to run the `make` command, but I got some trouble, I think because I'm on Windows. So I make a little search and I noticed that I could use nmake, and I tried, but when I tried to use the command `nmake test` the only result I received was 'tests are up-to-date', `make benchmark` returned 'permission denied'. Since I've never used this command before, I don't know how to fix it :/. Can you help me 
with it?

3 - Of course, I just create an issue (#34) :)


Thanks for your assistance!

**Comment by gumberss** [comment]
I'll fill v8 Version and Typescript Version when I'm home, I can't answer that off the top of my head

**Comment by asos-craigmorten** [comment]
> I'll fill v8 Version and Typescript Version when I'm home, I can't answer that off the top of my head

That's fab thanks - it doesn't matter too much, this affects all versions so the exact setup you have isn't so important 😄

**Comment by asos-craigmorten** [comment]
> Thanks for the advices :D!
> 
> 1 - Of course, I must add async to error_handler as well!
> 
> 2 - Before I create the pull request I tried to run the `make` command, but I got some trouble, I think because I'm on Windows. So I make a little search and I noticed that I could use nmake, and I tried, but when I tried to use the command `nmake test` the only result I received was 'tests are up-to-date', `make benchmark` returned 'permission denied'. Since I've never used this command before, I don't know how to fix it :/. Can you help me
> with it?
> 
> 3 - Of course, I just create an issue (#34) :)
> 
> Thanks for your assistance!

Amazing, thanks for raising this to my attention!

Apologies for your trouble with `make` - I'm on MacOS unfortunately and don't have a Windows PC to test with. Afaik it is possible to use `make` on Windows, but I've not had experience. A quick search implies you should be able to use package managers such as [chocolatey](https://chocolatey.org/) to install `make` using something like `choco install make`. It may be that ultimately more work is needed to make some of the commands cross-os!

If you struggle to figure out how to get make to work for your setup, you should be able to run the tests just using Deno commands 😄.

All `make ci` does is:

1. `deno fmt --check` - Just need to remember to run `deno fmt` before / after changes.
2. `deno run --lock=lock.json --reload mod.ts` - To ensure the lockfile is up to date.
3. `deno test --allow-net --allow-read` - Run all the tests.

Don't worry about the benchmarks, they are more for the CI and should always run without issue.

Thanks for raising the issue 🎉

**Comment by asos-craigmorten** [comment]
Ah it looks like CI is failing because of the lockfile is outdated - if you merge the `main` branch into yours this will likely resolve itself.

**Comment by gumberss** [comment]
I ran all the commands that you mentioned and I think it's all right, I performed the merge and created a test to ensure that there are no problems

please, if you want me to do another test or something like that, let me know :)

Thanks!!!

**Comment by asos-craigmorten** [comment]
Thanks @gumberss 💯 LGTM.

**Comment by asos-craigmorten** [comment]
Released in `0.15.0` 😄

**Pull request merged**
