### PR TITLE
(fix) deno 1.4.0 : export type

### PR DESCRIPTION
**Pull request by ThomasT404**
# Issue

With Deno 1.4.0 a problem prevents the library from being used and makes it necessary to use the "--isolatedModules" entry to work.

## Details

I changed all the exports and imports that were types to make it work.  
But libraries that Opine uses currently have the same problem, I am also looking at PRs fixes for their libs

### CODE REVIEW

**Comment by asos-craigmorten** [comment]
Hey @ThomasT404! 👋🏻 

Thanks so much 😄 on my todo list but not got round to it!

Look forward to seeing the deps fixed up so we can get this in!

**Comment by jvmazagao** [comment]
A lot of checks are broken, can anyone fix this merge?

**Comment by ThomasT404** [comment]
> A lot of checks are broken, can anyone fix this merge?

I just fixed the lock.json file 😄

**Review by jvmazagao — APPROVED** [review]

**Review by asos-craigmorten — APPROVED** [review]
LGTM 🥇

**Pull request merged**
